//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Currency_Calc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Value
    {
        public decimal Id { get; set; }
        public double Val { get; set; }
        public decimal IdRate { get; set; }
        public decimal Number { get; set; }
    
        public virtual Rate Rate { get; set; }
    }
}
